server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/incomedb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: INCOME-SERVICE
  config:
    import:
      config-server: http://localhost:9226
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-85124564.okta.com/oauth2/default
      client:
        registration:
          internal-client:
            provider: okta
            authorization-grant-type: client_credentials
            scope: internal
            client-id: 0oaellzhg13JwgO4N5d7
            client-secret: NXYbtP3sTq2kueu6qtmPZxaQ04SzSce6gcHmsMyHziWixXFVBiZyMqbYAOMqN37p
        provider:
          okta:
            issuer-uri: https://dev-85124564.okta.com/oauth2/default

management:
  tracing:
    sampling:
      probability: 1.0

resilience4j:
  circuitbreaker:
    instances:
      external:
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED